config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  resources :lists, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :image
  
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list.id)
    else
      render :new
    end
  end

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    @list.update(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :edit
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  private
  def list_params
    params.require(:list).permit(:title, :body, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <ul>
        <li><%= link_to "new", new_list_path %></li>
        <li><%= link_to "index", lists_path %></li>
      </ul>
    </header>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>投稿編集</h1>
<% if @list.errors.any? %>
  <%= @list.errors.count %>件のエラーが発生!
  <ul>
    <% @list.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @list, url: list_path, method: :patch do |f| %>
  <%= f.text_field :title %><br>
  <%= f.text_area :body %><br>
  <%= f.file_field :image, accept: "image/*" %>
  <%= f.submit "保存" %>
<% end %>

app/views/lists/index.html.erb
<h1>投稿一覧</h1>
<% @lists.each do |list| %>
  <p>Title</p>
  <%= link_to list_path(list) do %>
    <%= list.title %>
  <% end %>
  <p>Image</p>
  <% if list.image.attached? %>
    <%= image_tag list.image, size: "50x50" %>
  <% else %>
    <%= image_tag 'no_image',size: "50x50" %>
  <% end %>
<% end %>

app/views/lists/new.html.erb
<h1>新規投稿</h1>
<% if @list.errors.any? %>
 <%= @list.errors.count %>件のエラーが発生!
 <ul>
   <% @list.errors.full_messages.each do |message| %>
     <li><%= message %></li>
   <% end %>
 </ul>
<% end %>
<%= form_with model: @list, url:'/lists', method: :post do |f| %>
  <h3>Title</h3>
  <%= f.text_field :title %><br>
  <h3>Body</h3>
  <%= f.text_area :body %><br>
  <h3>画像</h3>
  <%= f.file_field :image, accept: "image/*" %>
  <%= f.submit "送信" %>
<% end %>

app/views/lists/show.html.erb
<h2>Title</h2>
<%= @list.title %>
<h2>Body</h2>
<%= @list.body %>
<h2>Image</h2>
<% if @list.image.attached? %>
  <%= image_tag @list.image, size: "50x50" %><br>
<% else %>
  <%= image_tag 'no_image', size: "50x50" %><br>
<% end %>
<%= link_to "edit", edit_list_path(@list) %><br>
<%= link_to "destroy", list_path(@list), method: :delete, "data-confirm" => "本当に削除しますか?" %>